### ISSUE TITLE
Pageant named pipe IPC support

### ISSUE THREAD

**Issue by themiron** [ndbeals/winssh-pageant#1]
Hello, many thanks for the project.
PuTTY/Pageant 0.74 supports named pipe transport for agent queries.

Simon's comment from [one of implementation commits ](https://git.tartarus.org/?p=simon/putty.git;a=commit;h=cf29125fb464169d1bab88a0bc9c18a4ca5a983a)
> Pageant runs a named-pipe server as well as a WM_COPYDATA
server, we prefer the former (if available) for agent forwarding, for
the same reasons as on Unix: it lets us establish a simple raw-data
streaming connection instead of agentf.c's complicated message
boundary detection and buffer management, and if agent connections
ever become stateful, this technique will cope.

Can this api be supported as well? Current pipe name format is here [windows/winpgntc.c:134](https://git.tartarus.org/?p=simon/putty.git;a=blob;f=windows/winpgntc.c;h=d9ca7b465f6477f4a04795981abdc6a34f89cc85;hb=HEAD#l134)

**Comment by ndbeals** [comment]
Yeah, I can do that. Though all I'm going to be doing is redirecting one named pipe to another `pipe\pageant` to `pipe\openssh-agent`. 

I see you have commits to PuTTY, so you may save me some time, whats does `capi_obfuscate_string("Pageant");` do? does it return the exact same string each time?

**Comment by ndbeals** [comment]
Also, do you know of a program that uses the pageant named pipes, so I may test?

**Comment by themiron** [comment]
> I see you have commits to PuTTY, so you may save me some time, whats does `capi_obfuscate_string("Pageant");` do? does it return the exact same string each time?

It's [putty-local function](https://git.tartarus.org/?p=simon/putty.git;a=blob;f=windows/wincapi.c;h=b18529224e9019ef98a625415cafd02b5012fc95;hb=HEAD#l54) with some comments inside:
> * CRYPTPROTECTMEMORY_CROSS_PROCESS causes CryptProtectMemory to
> * use the same key in all processes with this user id, meaning
> * that the next PuTTY process calling this function with the same
> * input will get the same data

So, at least it should be different per every user.

**Comment by themiron** [comment]
> Though all I'm going to be doing is redirecting one named pipe to another: `pipe\pageant` to `pipe\openssh-agent`.

I've tried to build PuTTY with just changed pipe name (to \\.\pipe\openssh-ssh-agent) to see how it works.
First of all, pipe existence checking is broken at least in my environment, if fix it - PuTTY fails to communicate with ssh-agent pipe as is

**Comment by ndbeals** [comment]
I finished this a few days ago but procrastinated. 

Here it is: no extra config options. It works on the setup I managed (i made npiperelay redirect to pageant pipe instead of openssh pipe). Let me know if it works for you on any programs that use this named new putty named pipe.

I wasn't able to get it to output an identical sha256, but I'm not sure if that even matters. Ultimately though I think any program implementing pageant named pipes should also make it look for the windows openssh pipe as well.

[winssh-pageant-v1.1_386.zip](https://github.com/ndbeals/winssh-pageant/files/5030356/winssh-pageant-v1.1_386.zip)
[winssh-pageant-v1.1_amd64.zip](https://github.com/ndbeals/winssh-pageant/files/5030357/winssh-pageant-v1.1_amd64.zip)

**Comment by themiron** [comment]
> I wasn't able to get it to output an identical sha256, but I'm not sure if that even matters
thanks, but pipe name must be identical over all processes for one user, or processes will be unable to communicate to pageant.
as it happens.

please refer code below, should give correct pipe suffix

```
import (
    "syscall"
    "unsafe"
    "crypto/sha256"
    "encoding/hex"
)

const CRYPTPROTECTMEMORY_BLOCK_SIZE    = 16
const CRYPTPROTECTMEMORY_CROSS_PROCESS = 1

var (
	crypt32                = syscall.NewLazyDLL("crypt32.dll")
	procCryptProtectMemory = crypt32.NewProc("CryptProtectMemory")
)

func capi_obfuscate_string(realname string) string {
	cryptlen := len(realname) + 1
	cryptlen += CRYPTPROTECTMEMORY_BLOCK_SIZE - 1
	cryptlen /= CRYPTPROTECTMEMORY_BLOCK_SIZE
	cryptlen *= CRYPTPROTECTMEMORY_BLOCK_SIZE

	cryptdata := make([]byte, cryptlen)
	copy(cryptdata, realname)

	pDataIn := uintptr(unsafe.Pointer(&cryptdata[0]))
	cbDataIn := uintptr(cryptlen)
	dwFlags := uintptr(CRYPTPROTECTMEMORY_CROSS_PROCESS)
	// pageant ignores errors
	procCryptProtectMemory.Call(pDataIn, cbDataIn, dwFlags)

	hash := sha256.Sum256(cryptdata)
	return hex.EncodeToString(hash[:])
}

**Comment by ndbeals** [comment]
That did it, thanks @themiron !

Updating to 1.1 release.

**Comment by themiron** [comment]
thanks, works perfectly.
please refer special build of PyTTY 0.74 with pipe IPC only for testing purposes
[putty64.zip](https://github.com/ndbeals/winssh-pageant/files/5044105/putty64.zip)

**Comment by thomasmey** [comment]
Hi, @ndbeals I tried to set the per user environment variable SSH_AUTH_SOCK to the pageant pipe file.
The SSH_DOCK_AUTH environment variable is used by docker cli to communicate with docker daemon.

But setting SSH_AUTH_SOCK environment per user doesn't work as each new user session/login seems to produce a new pipe file name, the suffix seems to change each time my computer restarts.

Any idea how to solve this problem?
