### ISSUE TITLE
Git ssh throws: get_agent_identities: ssh_fetch_identitylist: communication with agent failed

### ISSUE THREAD

**Issue by karypid** [ndbeals/winssh-pageant#18]
Hello,

I am trying to use your software so that Git-Bash can be used in concjuction with the Windows-bundled OpenSSH and its service.

I have installed the Windows-supplied service with: `Get-Service ssh-agent | Set-Service -StartupType Automatic -PassThru | Start-Service`. I added a key with ssh-add and now in PowerShell (where my path has `C:\WINDOWS\System32\OpenSSH\ssh.exe`) the password-less key exchange succeeds. When I access the host with `ssh -v user@host` I see:

```
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: C:\\Users\\myuser/.ssh/id_rsa RSA SHA256:{hash} agent
   ...
debug1: Offering public key: C:\\Users\\user/.ssh/id_rsa RSA SHA256:{hash}agent
debug1: Server accepts key: C:\\Users\\user/.ssh/id_rsa RSA SHA256:{hash}agent
debug1: Authentication succeeded (publickey).
```

I am also able to use this key in Putty (without running its own pageant) which means that putty successfully interacts with winssh-pageant successfully:

```
Using username "user".
Authenticating with public key "user@laptop" from agent
```

So now I am trying to use this with GIT for Windows which bundles ssh-pageant. But when I run this from GIT I get:

```
$ eval $(/usr/bin/ssh-pageant -r -a "/tmp/.ssh-pageant-$USERNAME")
ssh-pageant pid 1842

$ export | grep SSH_
declare -x SSH_ASKPASS="/mingw64/bin/git-askpass.exe"
declare -x SSH_AUTH_SOCK="/tmp/.ssh-pageant-user"
declare -x SSH_PAGEANT_PID="1842"

$ ssh -v user@host
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: get_agent_identities: ssh_get_authentication_socket: Connection refused
debug1: Will attempt key: /c/Users/user/.ssh/id_rsa RSA SHA256:{hash}
```

As you can see it seems that the agent proxying is not working? On powershell I see the following relevant named pipes:

```
> [System.IO.Directory]::GetFiles("\\.\\pipe\\")  | sls "ssh|ageant|msys"

\\.\\pipe\\openssh-ssh-agent
\\.\\pipe\\pageant.user.9895035fe9693621440ca5e7ab8c641ed24c692b06e0710d5117011bfe2a15
\\.\\pipe\\msys-82eb03937513ce77-16584-sigwait
\\.\\pipe\\msys-82eb03937513ce77-4276-sigwait
```

The `\\.\\pipe\\openssh-ssh-agent` is owned by the windows SSH agent (running as a service). The second one is owned by winssh-pageant, The last two are owned by git's ssh-pageant which supposedly should use the pageant protocol to grab keys for git's ssh...

Obviously this could be an issue with ssh-pageant instead, but is there some way to debug this from winssh-pageant side? Is it possible to run this in debug mode and see messages on the console regarding connections/requests for keys?

**Please note that:** if I use putty's pageant then git's ssh works fine. So if I stop winssh-pageant, load putty's pageant and then in git bash do:

```
$ eval $(/usr/bin/ssh-pageant -r -a "/tmp/.ssh-pageant-$USERNAME")
ssh-pageant pid 2143

$ ssh -v user@host
...
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: get_agent_identities: agent returned 1 keys
debug1: Will attempt key: /c/Users/user/.ssh/id_rsa RSA SHA256:{hash} agent
...
debug1: Offering public key: /c/Users/user/.ssh/id_rsa RSA SHA256:{hash} agent
debug1: Server accepts key: /c/Users/user/.ssh/id_rsa RSA SHA256:{hash} agent
Authenticated to host ([192.168.42.4]:22) using "publickey".
```

So at this point each one seems to work fine on its own, but the two in conjunction fail to work together. Not sure what the incompatibility could be.

Note that I am testing with Git for Windows 2.36.1.windows.1 version which bundles "OpenSSH_9.0p1, OpenSSL 1.1.1o  3 May 2022"

**Comment by karypid** [comment]
I just noticed that the problem is specific to Git for Windows 2.36.1.windows.1 

It appears that Git for Windows 2.35.1.windows.2 does not have the problem...

**Comment by karypid** [comment]
I tried the same with Cygwin. In fact the issue appears with openssh version 8.9. When I downgraded Cygwin to 8.8p1 it worked. Versions 8.9p1 and 9.0p1 do NOT work.

**Comment by karypid** [comment]
After installing the [latest version of the Microsoft OpenSSH packages](https://github.com/PowerShell/Win32-OpenSSH/releases) my problem changed into that GIT and Cygwin would get stuck forever talking to the agent.

In the end, I gave up and looked for alternatives. I came across [WinCryptSSHAgent](https://github.com/buptczq/WinCryptSSHAgent) which basically supports all protocols (Windows/WSL/Cygwin/MSYS) in one package. I've stopped running the Windows openssh service and use WinCryptSSHAgent exclusively.

**Comment by ndbeals** [comment]
Hello @karypid, thanks for trying this tool and for opening this issue. I commend your efforts trying to get this sorted out, you actually faced a couple different issues. I have a fix for the issue you reported, scroll past my explanations if you want to jump to the fix. If you're no longer interested in this because you're using WinCryptSSHAgent, feel free to close this issue.

The reason you're having this error in the first place is because git for windows packages it's own OpenSSH (as you've already noted). This causes issues because the git for windows OpenSSH is not aware of named pipes, it can't natively talk to the Microsoft OpenSSH.

You already tried fixing this by using ssh-pageant. The deadlock that happens here likely is due to winssh-pageant doing something wrong, and I've noted this and will look into it when I have time.

## The Fix

Uninstall Git For Windows, and reinstall it. you can set whatever install options you want except for when you get to "choose ssh executable step", you need to select "Use external ssh" option, see the image below.
![image](https://user-images.githubusercontent.com/850796/172498159-3027d754-7d8a-4271-ae6f-94a2bf0ef89a.png)

I suppose you could do that same thing without reinstalling by deleting `ssh` from `/usr/bin` too.

**Comment by karypid** [comment]
Hi @ndbeals ,

Thanks for your reply. I think that by choosing this option you end up using the native Windows client which would talk to the Windows agent directly (bypassing pageant protocol and thus winssh-pageant). While this will work, I also need cygwin to work with this. I could remove SSH from cygwin as well, but then I'm worried I may run into other issues by mixing native ssh with cygwin software.

For now I will stick to WinCryptSSHAgent.

Thank you!
