### ISSUE TITLE
Not working with net-ssh Ruby library

### ISSUE THREAD

**Issue by siccous** [ndbeals/winssh-pageant#3]
Hello,

I am using Capistrano to deploy some internal apps and it is internally using the Ruby net-ssh library for SSH connections. It works fine with pageant but recently I switched to using Windows OpenSSH agent thanks to your amazing library.

Everything works fine except this one use case. The pageant implementation from net-ssh library is here: https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/authentication/pageant.rb

**Comment by ndbeals** [comment]
Thanks for the feedback, I'll look into it, however I haven't used ruby before. 

Do you have demo/example code using that `net-ssh` library, and the instructions for how to get it running? It'd save me a lot of time!

**Comment by siccous** [comment]
You should be able to replicate it with this simple code:

`require 'net/ssh'

Net::SSH.start('host', 'user') do |ssh|
  output = ssh.exec!('hostname')
  puts output
end`

(replace host and user with appropriate values)

On Win you can install Ruby (2.6 version) through https://rubyinstaller.org, then you need to install net-ssh library, simple command `gem install net-ssh` should do it. And after that you can run my code with `C:\Ruby26-x64\bin\ruby.exe C:/net-ssh_test.rb`

Thanks.

**Comment by ndbeals** [comment]
Thanks for the response and help, I should be able to work on this by this weekend at the latest (I am moving this week). Cheers

**Comment by ndbeals** [comment]
Well, I wish I would've tried this earlier, Your sample code works for me @siccous.

It runs on both Ruby 2.6 and 2.7.

**Comment by siccous** [comment]
Okey, fixed.

It had nothing to do with your library. The reason was using outdated version of Win32-OpenSSH (I've used the version which is shipped now with recent Windows 10 version).

The solution was to install the newest (v8.0.0.0) version via Chocolatey and force the OpenSSH Authentication Agent service to use the new version.

Thanks again and sorry for this issue.

**Comment by ndbeals** [comment]
No worries! I'm happy you use my work and I appreciate you caring enough about it to improve it!

You make a good point about the MS Official OpenSSH packages though - I forgot I installed them from their github repo and not from windows update. I'll be sure to include a note about that on the README.

Unrelated question: How do you feel about the "task scheduler" auto-run? I'm thinking a secondary optional powershell script to install it may be appropriate.

**Comment by siccous** [comment]
Hello ndbeals,

sorry for my late answer. Is there any reason why we can't auto run it through Startup Folder shortcut?

If I remember it right I've tried it and it does not work 😄

**Comment by ndbeals** [comment]
No, @siccous, there shouldn't be anything preventing you, I just tried it and it works.

* Create a shortcut to the executable (right click -> create shortcut) 
* Put it in `C:\Users\<USER>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`
